apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prom-operator
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: prom-operator
  chart:
    git: git@github.com:helm/charts
    path: stable/prometheus-operator
    ref: master
  values:
    prometheus:
      podDisruptionBudget:
        enabled: true
    grafana:
      persistence:
        storageClassName: longhorn
        enabled: true
      ingress:
        enabled: true
        annotations: 
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
        - grafana.mcserverhosting.red
        tls:
        - hosts:
          - grafana.mcserverhosting.red
          secretName: grafana-cert
      grafana.ini:
        users:
          viewers_can_edit: false
        auth:
          disable_login_form: false
          disable_signout_menu: true
        auth.anonymous:
          enabled: true
          org_role: Viewer
          org_name: MC Server Hosting LLC




      