apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: nginx
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v0.15.2
  values:
    installCRDs: true
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: services@sfxworks.net
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
          ingressTemplate:
            metadata:
              annotations:
                "cert-manager": "http01"
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    email: services@sfxworks.net
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key-dns
    solvers:
    - dns01:
        acmedns:
          host: http://acme-dns.dns
          accountSecretRef:
            name: acme-dns
            key: acmedns.json
