apiVersion: v1
kind: Namespace
metadata:
  name: nginx
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: prom-operator
  chart:
    git: git@github.com:helm/charts
    path: stable/nginx-ingress
    ref: master