apiVersion: v1
kind: Namespace
metadata:
  name: nginx
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: nginx
  chart:
    git: git@github.com:helm/charts
    path: stable/nginx-ingress
    ref: master
  values:
    controller:
      service:
        ports:
          http: 80
          https: 443
          pop3: 110
          pop3s: 995
          imap: 143
          imaps: 993
          smtp: 25
          smtps: 465
          smtpd: 587
        targetPorts:
          http: http
          https: https
          pop3: pop3
          pop3s: pop3s
          imap: imap
          imaps: imaps
          smtp: smtp
          smtps: smtps
          smtpd: smtpd
    tcp:
      110: "mail/mail-mailu-front:110"
      995: "mail/mail-mailu-front:995"
      143: "mail/mail-mailu-front:143"
      993: "mail/mail-mailu-front:993"
      25: "mail/mail-mailu-front:25"
      465: "mail/mail-mailu-front:465"
      587: "mail/mail-mailu-front:587"
