apiVersion: v1
kind: ServiceAccount
metadata:
  name: mc-router
  namespace: mcsh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: services-watcher
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mc-router-services-watcher
subjects:
- kind: ServiceAccount
  name: mc-router
  namespace: default
roleRef:
  kind: ClusterRole
  name: services-watcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: mc-router-tcp
  namespace: mcsh
  annotations:
    metallb.universe.tf/allow-shared-ip: "mcrouter"
spec:
  type: LoadBalancer
  loadBalancerIP: "51.222.70.233"
  ports:
  - targetPort: proxy-tcp
    name: proxy
    port: 25565
    protocol: TCP
  selector:
    run: mc-router
---
apiVersion: v1
kind: Service
metadata:
  name: mc-router-udp
  namespace: mcsh
  annotations:
    metallb.universe.tf/allow-shared-ip: "mcrouter"
spec:
  type: LoadBalancer
  loadBalancerIP: "51.222.70.233"
  ports:
  - targetPort: proxy-udp
    name: proxy
    port: 25565
    protocol: UDP
  selector:
    run: mc-router
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: mc-router
  name: mc-router
  namespace: mcsh
spec:
  selector:
    matchLabels:
      run: mc-router
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: mc-router
    spec:
      serviceAccountName: mcsh-operator
      containers:
      - image: itzg/mc-router:1.10.2
        terminationMessagePolicy: FallbackToLogsOnError
        name: mc-router
        args: ["--api-binding", ":8080", "--in-kube-cluster"]
        ports:
        - name: proxy-tcp
          containerPort: 25565
          protocol: TCP
        - name: proxy-udp
          containerPort: 25565
          protocol: UDP
        resources:
          requests:
            memory: 250Mi
            cpu: "500m"
          limits:
            memory: 250Mi
            cpu: "500m"
