apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcsh-operator
  namespace: mcsh
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mcsh-operator
  namespace: mcsh
subjects:
- kind: ServiceAccount
  name: mcsh-operator
  namespace: mcsh
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcsh-operator
  namespace: mcsh
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mcsh-operator
  template:
    metadata:
      labels:
        name: mcsh-operator
    spec:
      serviceAccountName: mcsh-operator
      containers:
      - name: mcsh-operator
        image: docker.io/quantomwor ks/mc-operator:v3.4
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "mcsh-operator"
