---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bungee-op
  namespace: mcsh
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bungee-op
  template:
    metadata:
      labels:
        name: bungee-op
    spec:
      serviceAccountName: bungee-op
      containers:
      - name: bungee-op
        resources:
          requests:
            memory: 250Mi
            cpu: 250m
          limits:
            memory: 500Mi
            cpu: 500m
        image: docker.io/quantomworks/mcsh-bungee-operator:v3.2
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "bungee-op"
