kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bungee-op
  namespace: mcsh
subjects:
- kind: ServiceAccount
  name: bungee-op
roleRef:
  kind: Role
  name: bungee-op
  apiGroup: rbac.authorization.k8s.io
