apiVersion: v1
kind: Service
metadata:
  name: rook-prometheus
  namespace: rook-ceph
spec:
  type: ClusterIP
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: rook-prometheus
