apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: s3-ingress
  namespace: rook-ceph
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  rules:
  - host: s3.mcserverhosting.red
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: rook-ceph-rgw-mcsh-store
          servicePort: 80
  tls: 
  - hosts:
    - s3.mcserverhosting.red
    secretName: s3-cert
