apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-rgw-mcsh-store-external
  namespace: rook-ceph
  labels:
    app: rook-ceph-rgw
    rook_cluster: rook-ceph
    rook_object_store: mcsh-store
spec:
  ports:
  - name: rgw
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rook-ceph-rgw
    rook_cluster: rook-ceph
    rook_object_store: mcsh-store
  sessionAffinity: None
  type: LoadBalancer
