---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-coredns
  labels:
    app.kubernetes.io/name: coredns
data:
  Corefile: |-
    . {
        log
        errors
        health {
            lameduck 5s
        }
        ready
        cache 30
        loop
        reload
        etcd {
            stubzones
            path /skydns
            endpoint http://etcd-coredns-client:2379
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-coredns
  labels:
    app.kubernetes.io/name: coredns
spec:
  loadBalancerIP: "51.222.70.235"
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: coredns
  ports:
  - port: 53
    protocol: UDP
    name: udp-53
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-coredns
  labels:
    app.kubernetes.io/name: coredns
spec:
  loadBalancerIP: "51.222.70.235"
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: coredns
  ports:
  - port: 53
    protocol: TCP
    name: tcp-53
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns-coredns
  labels:
    app.kubernetes.io/name: coredns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 10%
  selector:
    matchLabels:
      app.kubernetes.io/name: coredns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: coredns
    spec:
      serviceAccountName: default
      containers:
      - name: "coredns"
        image: "coredns/coredns:1.7.0"
        imagePullPolicy: IfNotPresent
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 53
          protocol: UDP
          name: udp-53
        - containerPort: 53
          protocol: TCP
          name: tcp-53
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      volumes:
        - name: config-volume
          configMap:
            name: coredns-coredns
            items:
            - key: Corefile
              path: Corefile