apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: coredns
  namespace: dns
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: coredns
  chart:
    git: git@github.com:helm/charts
    path: stable/coredns
    ref: master
  values:
    serviceType: "LoadBalancer"
    service:
      loadBalancerIP: "51.222.70.235"
      externalTrafficPolicy: "Local"
    isClusterService: false
    servers:
    - zones:
      - zone: .
      port: 53
      plugins:
      - name: log
      - name: errors
      - name: health
        configBlock: |-
          lameduck 5s
      - name: ready
      # Serves a /metrics endpoint on :9153, required for serviceMonitor
      - name: forward
        parameters: . /etc/resolv.conf
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
      - name: etcd
        parameters: 
        configBlock: |-
          stubzones
          path /skydns
          endpoint http://etcd-coredns-client:2379