apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  name: etcd-coredns
  namespace: dns
  annotations:
    etcd.database.coreos.com/scope: clusterwide
spec:
  size: 1
  version: 3.2.13
