apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: general-endpoints
spec:
  endpoints:
  - dnsName: cluster.mcserverhosting.red
    recordTTL: 180
    recordType: A
    targets:
    - 51.79.102.159
  - dnsName: play.mcserverhosting.red
    recordTTL: 180
    recordType: A
    targets:
    - 51.222.70.233
  - dnsName: ssh.mcserverhosting.red
    recordTTL: 180
    recordType: A
    targets:
    - 51.79.102.159
  - dnsName: ns1.mcserverhosting.red
    recordTTL: 180
    recordType: A
    targets:
    - 51.222.70.240
  - dnsName: ns2.mcserverhosting.red
    recordTTL: 180
    recordType: A
    targets:
    - 51.222.70.240
  - dnsName: _acme-challenge.mcserverhosting.red
    recordTTL: 180
    recordType: CNAME
    targets:
    - d2c70604-17cc-4122-b12e-786b2740d398.mcserverhosting.red
  - dnsName: test.mcserverhosting.red
    recordTTL: 180
    recordType: CNAME
    targets:
    - mcserverhosting.net
