apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: minecraftservers.mcserverhosting.net
spec:
  group: mcserverhosting.net
  names:
    kind: MinecraftServer
    shortNames:
    - mcserver
    - mcs
    - mc
    - mcservers
    - mcserv
    listKind: MinecraftServerList
    plural: minecraftservers
    singular: minecraftserver
  scope: Namespaced
  versions:
  - name: v2
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
