apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prom-operator
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: prom-operator
  chart:
    git: git@github.com:helm/charts
    path: stable/prometheus-operator
    ref: master