---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-op
  namespace: mcsh
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: server-op
  template:
    metadata:
      labels:
        name: server-op
    spec:
      serviceAccountName: server-op
      containers:
      - name: server-op
        resources:
          requests:
            memory: 500Mi
            cpu: 100m
          limits:
            memory: 500Mi
            cpu: 250m
        image: harbor.mcserverhosting.red/mcsh/server-operator:v1.3.6
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: IP
          value: "51.222.70.233"
        - name: TLD
          value: mcsh.red
        - name: RUNTIME
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "server-op"
