kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: server-op
subjects:
- kind: ServiceAccount
  name: server-op
  namespace: mcsh
roleRef:
  kind: ClusterRole
  name: server-op
  apiGroup: rbac.authorization.k8s.io
