apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mcsh
  namespace: mcsh
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/limit-connections: '4'
    nginx.ingress.kubernetes.io/limit-rpm: '240'
    nginx.ingress.kubernetes.io/server-snippet: |
      set_real_ip_from 103.21.244.0/22;
      set_real_ip_from 103.22.200.0/22;
      set_real_ip_from 103.31.4.0/22;
      set_real_ip_from 104.16.0.0/12;
      set_real_ip_from 108.162.192.0/18;
      set_real_ip_from 131.0.72.0/22;
      set_real_ip_from 141.101.64.0/18;
      set_real_ip_from 162.158.0.0/15;
      set_real_ip_from 172.64.0.0/13;
      set_real_ip_from 173.245.48.0/20;
      set_real_ip_from 188.114.96.0/20;
      set_real_ip_from 190.93.240.0/20;
      set_real_ip_from 197.234.240.0/22;
      set_real_ip_from 198.41.128.0/17;
      set_real_ip_from 2400:cb00::/32;
      set_real_ip_from 2606:4700::/32;
      set_real_ip_from 2803:f800::/32;
      set_real_ip_from 2405:b500::/32;
      set_real_ip_from 2405:8100::/32;
      set_real_ip_from 2c0f:f248::/32;
      set_real_ip_from 2a06:98c0::/29;
      real_ip_header CF-Connecting-IP;
spec:
  tls:
  - hosts:
    - mcserverhosting.net
    - www.mcserverhosting.net
    secretName: mcserverhostingnet
  rules:
  - host: mcserverhosting.net
    http:
      paths:
      - path: /
        backend:
          serviceName: site
          servicePort: 80
      - path: /support
        pathType: Prefix
        backend:
          serviceName: support
          servicePort: 80
  - host: www.mcserverhosting.net
    http:
      paths:
      - path: /
        backend:
          serviceName: site
          servicePort: 80
      - path: /support
        pathType: Prefix
        backend:
          serviceName: support
          servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mcsh-discord
  namespace: mcsh
  annotations:
    nginx.ingress.kubernetes.io/limit-connections: '4'
    nginx.ingress.kubernetes.io/limit-rpm: '240'
    nginx.ingress.kubernetes.io/temporal-redirect: https://discord.gg/vzwCs8K
spec:
  tls:
  - hosts:
    - mcserverhosting.net
    - www.mcserverhosting.net
    secretName: mcserverhostingnet
  rules:
  - host: mcserverhosting.net
    http:
      paths:
      - path: /discord
        backend:
          serviceName: site
          servicePort: 80
  - host: www.mcserverhosting.net
    http:
      paths:
      - path: /discord
        backend:
          serviceName: site
          servicePort: 80