---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp-op
  namespace: mcsh
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sftp-op
  template:
    metadata:
      labels:
        name: sftp-op
    spec:
      serviceAccountName: sftp-op
      containers:
      - name: sftp-op
        resources:
          requests:
            memory: 500Mi
            cpu: 100m
          limits:
            memory: 500Mi
            cpu: 250m
        image: harbor.mcserverhosting.red/mcsh/sftp-operator:v1.3
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "sftp-op"
