kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sftp-op
subjects:
- kind: ServiceAccount
  name: sftp-op
roleRef:
  kind: ClusterRole
  name: sftp-op
  apiGroup: rbac.authorization.k8s.io
