kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sftp-op
  namespace: mcsh
subjects:
- kind: ServiceAccount
  name: sftp-op
roleRef:
  kind: Role
  name: sftp-op
  apiGroup: rbac.authorization.k8s.io
