apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mailu
  namespace: mail
  annotations:
    fluxcd.io/automated: "true"
    custom-branch: "true"
spec:
  chart:
    git: git@github.com:sfxworks/mailu-helm
    path: mailu
    ref: sfxworks-patch1
  valuesFrom:
  - secretKeyRef:
      name: mailu
      namespace: mail
      key: mailu-default.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    linkerd.io/inject: enabled
    custom-branch: "true"
  name: mail