apiVersion: apps/v1
kind: Deployment
metadata:
  name: nslock-op
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nslock-op
  template:
    metadata:
      labels:
        name: nslock-op
    spec:
      serviceAccountName: nslock-op
      containers:
      - name: nslock-op
        resources:
          requests:
            memory: 50Mi
            cpu: 50m
          limits:
            memory: 100Mi
            cpu: 100m
        image: docker.io/quantomworks/nslock-operator
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "nslock-op"
